
on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
       node-version: ${{ env.NODE_VERSION }}
    - name: Install newman
      run: | 
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    - name: executar
      run: newman run marvel.json -e Herois.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
    - name: Make Directory for results
      run: mkdir -p testResults
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults
    
